SELECT 
    C.NOM_CLIENTE AS NOME_CLIENTE,
    P.DAT_EMISSAO AS DATA_EMISSÃO,
    P.VAL_TOTAL AS VALOR_TOTAL,
    (SELECT SUM(P2.VAL_TOTAL) 
     FROM TB_PEDIDO P2 
     WHERE P2.ID_CLIENTE = P.ID_CLIENTE 
     AND P2.DAT_EMISSAO <= P.DAT_EMISSAO) AS TOTAL_ACUMULADO
FROM 
    TB_CLIENTE C
INNER JOIN 
    TB_PEDIDO P ON C.ID_CLIENTE = P.ID_CLIENTE
ORDER BY 
    C.NOM_CLIENTE, P.DAT_EMISSAO;