/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_TB_PEDIDO_TB_CLIENTE]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [TB_PEDIDO] DROP CONSTRAINT [FK_TB_PEDIDO_TB_CLIENTE]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_TB_PEDIDO_ITEM_TB_PEDIDO]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [TB_PEDIDO_ITEM] DROP CONSTRAINT [FK_TB_PEDIDO_ITEM_TB_PEDIDO]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_TB_PEDIDO_ITEM_TB_PRODUTO]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [TB_PEDIDO_ITEM] DROP CONSTRAINT [FK_TB_PEDIDO_ITEM_TB_PRODUTO]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TB_CLIENTE]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TB_CLIENTE]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TB_PEDIDO]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TB_PEDIDO]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TB_PEDIDO_ITEM]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TB_PEDIDO_ITEM]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[TB_PRODUTO]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [TB_PRODUTO]
GO

/* Create Tables */

CREATE TABLE [TB_CLIENTE]
(
	[ID_CLIENTE] bigint NOT NULL IDENTITY (1, 1),
	[COD_CLIENTE] varchar(10) NULL,
	[NOM_CLIENTE] varchar(100) NULL,
	[NOM_CIDADE] varchar(100) NULL,
	[COD_UF] varchar(2) NULL
)
GO

CREATE TABLE [TB_PEDIDO]
(
	[ID_PEDIDO_VENDA] bigint NOT NULL IDENTITY (1, 1),
	[ID_CLIENTE] bigint NULL,
	[DAT_EMISSAO] date NULL,
	[VAL_TOTAL] real NULL
)
GO

CREATE TABLE [TB_PEDIDO_ITEM]
(
	[ID_PEDIDO_VENDA_ITEM] bigint NOT NULL IDENTITY (1, 1),
	[ID_PEDIDO_VENDA] bigint NULL,
	[ID_PRODUTO] bigint NULL,
	[QTD_ITEM] real NULL,
	[VAL_UNITARIO] real NULL,
	[VAL_ITEM] real NULL
)
GO

CREATE TABLE [TB_PRODUTO]
(
	[ID_PRODUTO] bigint NOT NULL IDENTITY (1, 1),
	[COD_PRODUTO] varchar(10) NULL,
	[NOM_PRODUTO] varchar(100) NULL,
	[VAL_PRECO_VENDA] real NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [TB_CLIENTE] 
 ADD CONSTRAINT [PK_TB_CLIENTE]
	PRIMARY KEY CLUSTERED ([ID_CLIENTE] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_TB_CLIENTE_01] 
 ON [TB_CLIENTE] ([ID_CLIENTE] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_TB_CLIENTE_02] 
 ON [TB_CLIENTE] ([COD_CLIENTE] ASC)
GO

ALTER TABLE [TB_PEDIDO] 
 ADD CONSTRAINT [PK_TB_PEDIDO]
	PRIMARY KEY CLUSTERED ([ID_PEDIDO_VENDA] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_TB_PEDIDO_TB_CLIENTE] 
 ON [TB_PEDIDO] ([ID_CLIENTE] ASC)
GO

ALTER TABLE [TB_PEDIDO_ITEM] 
 ADD CONSTRAINT [PK_TB_PEDIDO_ITEM]
	PRIMARY KEY CLUSTERED ([ID_PEDIDO_VENDA_ITEM] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_TB_PEDIDO_ITEM_TB_PEDIDO] 
 ON [TB_PEDIDO_ITEM] ([ID_PEDIDO_VENDA] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_TB_PEDIDO_ITEM_TB_PRODUTO] 
 ON [TB_PEDIDO_ITEM] ([ID_PRODUTO] ASC)
GO

ALTER TABLE [TB_PRODUTO] 
 ADD CONSTRAINT [PK_TB_PRODUTO]
	PRIMARY KEY CLUSTERED ([ID_PRODUTO] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_TB_PRODUTO_01] 
 ON [TB_PRODUTO] ([ID_PRODUTO] ASC)
GO

CREATE NONCLUSTERED INDEX [IDX_TB_PRODUTO_02] 
 ON [TB_PRODUTO] ([COD_PRODUTO] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [TB_PEDIDO] ADD CONSTRAINT [FK_TB_PEDIDO_TB_CLIENTE]
	FOREIGN KEY ([ID_CLIENTE]) REFERENCES [TB_CLIENTE] ([ID_CLIENTE]) ON DELETE CASCADE
GO

ALTER TABLE [TB_PEDIDO_ITEM] ADD CONSTRAINT [FK_TB_PEDIDO_ITEM_TB_PEDIDO]
	FOREIGN KEY ([ID_PEDIDO_VENDA]) REFERENCES [TB_PEDIDO] ([ID_PEDIDO_VENDA]) ON DELETE CASCADE
GO

ALTER TABLE [TB_PEDIDO_ITEM] ADD CONSTRAINT [FK_TB_PEDIDO_ITEM_TB_PRODUTO]
	FOREIGN KEY ([ID_PRODUTO]) REFERENCES [TB_PRODUTO] ([ID_PRODUTO])
GO

INSERT INTO TB_CLIENTE (COD_CLIENTE, NOM_CLIENTE, NOM_CIDADE, COD_UF)
VALUES
    ('CLI001', 'João Silva', 'São Paulo', 'SP'),
    ('CLI002', 'Maria Rodrigues', 'Rio de Janeiro', 'RJ'),
    ('CLI003', 'Pedro Oliveira', 'Belo Horizonte', 'MG'),
    ('CLI004', 'Ana Souza', 'Brasília', 'DF'),
    ('CLI005', 'Carlos Santos', 'Porto Alegre', 'RS');

GO

INSERT INTO TB_PEDIDO (ID_CLIENTE, DAT_EMISSAO, VAL_TOTAL)
VALUES
    (1, '2022-01-01', 100.00),
    (2, '2022-01-15', 200.00),
    (3, '2022-02-01', 50.00),
    (1, '2022-03-01', 150.00),
    (4, '2022-04-01', 300.00);

GO
INSERT INTO TB_PRODUTO (COD_PRODUTO, NOM_PRODUTO, VAL_PRECO_VENDA)
VALUES
    ('PROD001', 'Produto A', 20.00),
    ('PROD002', 'Produto B', 30.00),
    ('PROD003', 'Produto C', 10.00),
    ('PROD004', 'Produto D', 50.00),
    ('PROD005', 'Produto E', 40.00);
GO
INSERT INTO TB_PEDIDO_ITEM (ID_PEDIDO_VENDA, ID_PRODUTO, QTD_ITEM, VAL_UNITARIO, VAL_ITEM)
VALUES
    (1, 1, 2, 20.00, 40.00),
    (1, 2, 1, 30.00, 30.00),
    (2, 3, 3, 10.00, 30.00),
    (3, 1, 1, 20.00, 20.00),
    (4, 4, 2, 50.00, 100.00),
    (5, 2, 1, 30.00, 30.00),
    (5, 5, 1, 40.00, 40.00),
    (1, 3, 1, 10.00, 10.00),
    (2, 1, 1, 20.00, 20.00),
    (3, 4, 1, 50.00, 50.00);
GO

SELECT * FROM TB_CLIENTE;
GO
SELECT * FROM TB_PEDIDO;
GO
SELECT * FROM TB_PRODUTO;
GO
SELECT * FROM TB_PEDIDO_ITEM;